### ISSUE TITLE
Feature Request: username selection command line option

### ISSUE THREAD

**Issue by HamishMacEwan** [twitter/twurl#10]
Hi,

The two step process to ensure the correct username is used (in a script for example):

twurl set default username
twurl tweet -d status="why's that?"

Seems a bit awkward.  Couldn't -u be used for this or that would be curly?

**Comment by AgoraSecurity** [comment]
+1

**Comment by AgoraSecurity** [comment]
If it helps someone, I created this small ruby code that helps achieve the goal:
```
require 'twurl'

path = "/1.1/account/verify_credentials.json?include_entities=false&skip_status=true"

options = Twurl.options.dup
options.command = "get"
options.path = path
options.data = []
client = Twurl::OAuthClient.load_client_for_username(username)

Twurl::RequestController.dispatch(client, options)

```

**Comment by smaeda-ks** [comment]
created https://github.com/twitter/twurl/pull/125

**Comment by smaeda-ks** [comment]
This is merged into master.

**Comment by smaeda-ks** [comment]
https://github.com/twitter/twurl/releases/tag/v0.9.4

Closing.
