### ISSUE TITLE
Unable to write data into a file (-f &-F commands)

### ISSUE THREAD

**Issue by pvkrajj** [twitter/twurl#112]
I am trying to use below command and I want to write all the data into an external file how ever nothing is working not getting how to use -f , --file & -F, --file-field commands 

twurl /1.1/followers/list.json?cursor=-1&screen_name=pvkrajj --file C:\Users\pvkraa\Desktop\tmp.json

**Comment by andypiper** [comment]
The `-f` options are for use when taking data from a file to POST to the Twitter API. They are not intended for saving data into a file.

You should use the standard terminal redirect syntax for your operating system. On Windows, this is the `>` operator. Read more [here](https://helpdeskgeek.com/how-to/redirect-output-from-command-line-to-text-file/).
