### ISSUE TITLE
Ubuntu 10.10 install issues

### ISSUE THREAD

**Issue by iqbalmohomed** [twitter/twurl#12]
I'm having trouble getting twurl to install cleanly on Ubuntu 10.10. Unfortunately, I've never touched Ruby and am having trouble figuring out the issue (wasted a day so far and feel like I made zero progress diagnosing the problem). I managed to get twurl working perfectly on my snow leopard laptop on the first go. Is there a linux distro you can recommend ... one where Ruby/twurl installs cleanly?

FYI ... the issue with Ubuntu is odd. First off, I can't seem to update gem. It is 1.3.7 on my Ubuntu box but 1.4.1 on my Mac. When I used the install commands for twurl, I see a success message on Ubuntu:

sudo gem i twurl --source http://rubygems.org
Successfully installed twurl-0.6.2
1 gem installed
Installing ri documentation for twurl-0.6.2...
Installing RDoc documentation for twurl-0.6.2...

However, when I do "which twurl", I don't see anything. On Mac, I see:
/usr/bin/twurl

I'd really appreciate an alternative distro recommendation and/or help getting this to work on Ubuntu.

P.S. Thanks for this excellent tool.

**Comment by andypiper** [comment]
Closing for age / inability to repro - please open a new issue if this still occurs with 0.9.3
