### ISSUE TITLE
Supporting API search

### ISSUE THREAD

**Issue by ghost** [twitter/twurl#13]
I am not sure if twurl supports the search API. If it does I can not figure out how to use it. I have tried
twurl 'q=the' search.twitter.com/search.json
and
twurl 'http://search.twitter.com/search.json?q=the'
any advice would be greatly appreciated.

**Comment by jcanales** [comment]
I used this `$ twurl -d /1.1/search/tweets.json?q="your search criteria` hope it can help you

**Comment by andypiper** [comment]
Original question refers to a very outdated API endpoint - twurl works fine with the 1.1 Search API.
