### ISSUE TITLE
`expand_path': couldn't find login name -- expanding `~' (ArgumentError)

### ISSUE THREAD

**Issue by edipoReboucas** [twitter/twurl#142]
I'm trying use [Support authorization options on request ](https://github.com/twitter/twurl/pull/131)

When I run with a user without `$HOME` directory, in the case www-data (apache user),  I'm getting the error:

```
/var/lib/gems/2.5.0/gems/twurl-0.9.5/lib/twurl/rcfile.rb:6:in `expand_path': couldn't find login name -- expanding `~' (ArgumentError)
	from /var/lib/gems/2.5.0/gems/twurl-0.9.5/lib/twurl/rcfile.rb:6:in `directory'
	from /var/lib/gems/2.5.0/gems/twurl-0.9.5/lib/twurl/rcfile.rb:14:in `file_path'
	from /var/lib/gems/2.5.0/gems/twurl-0.9.5/lib/twurl/rcfile.rb:18:in `load'
	from /var/lib/gems/2.5.0/gems/twurl-0.9.5/lib/twurl/rcfile.rb:30:in `initialize'
	from /var/lib/gems/2.5.0/gems/twurl-0.9.5/lib/twurl/oauth_client.rb:6:in `new'
	from /var/lib/gems/2.5.0/gems/twurl-0.9.5/lib/twurl/oauth_client.rb:6:in `rcfile'
	from /var/lib/gems/2.5.0/gems/twurl-0.9.5/lib/twurl/oauth_client.rb:12:in `load_from_options'
	from /var/lib/gems/2.5.0/gems/twurl-0.9.5/lib/twurl/cli.rb:25:in `dispatch'
	from /var/lib/gems/2.5.0/gems/twurl-0.9.5/lib/twurl/cli.rb:21:in `run'
	from /var/lib/gems/2.5.0/gems/twurl-0.9.5/bin/twurl:4:in `<top (required)>'
	from /usr/local/bin/twurl:23:in `load'
	from /usr/local/bin/twurl:23:in `<main>'
```

I belive that is correlated this bug in another ruby project.

[# fixes: couldn't find login name expanding tilde (cont.)](https://github.com/sensu/sensu-puppet/pull/1082/commits/46af93aab03cf41aa086797849f9819ee555c048)

As workaround,  I change RCFile class

```rb
module Twurl
  class RCFile
    FILE = '.twurlrc'
    class << self
      def directory
        @@directory ||= '' 
        #@@directory ||= File.expand_path('~')
```

### Expected behavior

Send request without `.twurlrc ` file

### Actual behavior

twurl crash and print a error message

### Steps to reproduce the behavior

- install a php + apache setup on linux
- install twurl
- create php script with a `shell_exec` command executing twurl with all authentication options

**Comment by smaeda-ks** [comment]
@edipoReboucas Thanks. For me, the proper fix is to rewrite this logic:
https://github.com/twitter/twurl/blob/master/lib/twurl/oauth_client.rb#L12-L26

there are too many if conditions and it should be simplified. I'll look into this and open a PR later.
