### ISSUE TITLE
Username and password are not valid for Twitter auth

### ISSUE THREAD

**Issue by andypiper** [twitter/twurl#144]
twurl continues to maintain -u and -p options for username and password - this authentication method has not been available for many years, so this should be removed.

**Comment by smaeda-ks** [comment]
Note: we can deprecate `-p` option for sure but not `-u` option as it can be used to specify which user's secret/token from ~/.twurlrc to be used.

**Comment by andypiper** [comment]
Great point, I completely forgot we needed it for that!
