### ISSUE TITLE
Install fails on CentOS7: twurl requires Ruby version >= 2.4.0

### ISSUE THREAD

**Issue by minfrin** [twitter/twurl#148]
Install fails on fully up to date CentOS7 machine.

### Expected behavior

Install succeeds with no issues.

### Actual behavior

Install fails as follows:

```
-bash-4.2$ gem install twurl
Fetching: oauth-0.5.4.gem (100%)
Successfully installed oauth-0.5.4
Fetching: twurl-0.9.5.gem (100%)
ERROR:  Error installing twurl:
	twurl requires Ruby version >= 2.4.0.
```

### Steps to reproduce the behavior

- On a CentOS7 machine
- Run "gem install twurl".

**Comment by andypiper** [comment]
what version of Ruby is available on that system, please?

**Comment by minfrin** [comment]
CentOS7 ships with this:

```
 ruby                                           x86_64                             2.0.0.648-36.el7                                base                              73 k
```

**Comment by andypiper** [comment]
Unfortunately Twurl 0.9.5 requires a newer Ruby runtime (per the error message). You could try using rbenv or rvm to update to a more recent version -> https://linuxize.com/post/how-to-install-ruby-on-centos-7/

**Comment by minfrin** [comment]
This is like demolishing your house and rebuilding it, just to change the TV channel.

Is there a way to widen the dependency list on Ruby to support widely installed versions, or is the Ruby API not stable enough to do that?

**Comment by andypiper** [comment]
We needed to move to a newer version of Ruby in order to add more recent features and resolve some issues. The last version of `twurl` that supported Ruby < 2.4 was version 0.9.3 released in 2015 - you should find that it will work, but not all of the current features will be available. 

```gem install twurl -v 0.9.3```

**Comment by andypiper** [comment]
Ruby 2.4.0 itself is [out of support](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/), so I'm going to close this issue at this point.
