### ISSUE TITLE
When will the "`expand_path': couldn't find login name -- expanding `~' (ArgumentError)" get fixed?

### ISSUE THREAD

**Issue by RiversideRocks** [twitter/twurl#151]
Hello,

I have ran into the exact same here as issue #142, except I am using the exec() function VS the shell_exec() function. Is there an easy workaround for the moment?

**Comment by smaeda-ks** [comment]
cc: @andypiper 
https://github.com/twitter/twurl/pull/145 would suppress this error.

**Comment by andypiper** [comment]
Should be resolved in v0.9.6 just released
