### ISSUE TITLE
Authenticated successfully but getting invalid or expired token on API call

### ISSUE THREAD

**Issue by paololazzari** [twitter/twurl#176]
I authenticated successfully:

```bash
$ twurl authorize --consumer-key xxx --consumer-secret xxx
Authorization successful
```

then, tried to run the following:

```bash
$ twurl /1.1/statuses/home_timeline.json
{"errors":[{"code":89,"message":"Invalid or expired token."}]}
```

**Comment by andypiper** [comment]
Just to clarify, and we don't need to see the whole process, but can you confirm that when you ran `twurl authorize`, you then went through a PIN-based authentication process involving the web browser and the terminal? And that `twurl accounts` shows you have a default account and that your `.twurlrc` file contains account secret and token (please do not share these)

**Comment by andypiper** [comment]
Additionally, if you have a new Twitter Developer Account, do you have access to the v1.1 API (elevated access)

**Comment by paololazzari** [comment]
@andypiper Thank you for your reply. It looks like the culprit was the `twurlc` file; for some reason the `default_profile` was pointing to the wrong profile. As soon as I changed the default profile the API call worked as expected.

**Comment by andypiper** [comment]
FWIW you can use `twurl accounts` and `twurl set default` to fix that if you don't want to edit the hidden file manually. Good to know things are working!
