### ISSUE TITLE
Issue when i try authz 

### ISSUE THREAD

**Issue by bao3** [twitter/twurl#27]
/usr/lib/ruby/1.8/net/http.rb:560:in `initialize': getaddrinfo: Name or service not known (SocketError)

i use my own host , linke this:

twurl authorize -u myname -p passwd --consumer-key Xdhr9Hz7DOw --consumer-secret 2TnM  -H https://baga3.org/b3tt/t/

**Comment by andypiper** [comment]
Closing for age / inability to repro - please open a new issue if this still occurs with 0.9.3
