### ISSUE TITLE
How to handle timeout issue

### ISSUE THREAD

**Issue by sp88011** [twitter/twurl#36]
I'm using twurl via the Mac Terminal and everything works fine except that I get timeout errors (for certain keywords) when accessing the search API. Is there anyway to rescue these timeout errors or set the timeout-treshold higher?

twurl -t -d track='very_rare_keyword'  -H stream.twitter.com /1.1/statuses/filter.json >filename.json

yields (after roughly have a minute)

/usr/lib/ruby/1.8/timeout.rb:64:in `rbuf_fill': execution expired (Timeout::Error)
    from /usr/lib/ruby/1.8/net/protocol.rb:134:in`rbuf_fill'
    from /usr/lib/ruby/1.8/net/protocol.rb:104:in `read_all'
    from /usr/lib/ruby/1.8/net/http.rb:2228:in`read_body_0'
    from /usr/lib/ruby/1.8/net/http.rb:2181:in `read_body'
    from /usr/lib/ruby/gems/1.8/gems/twurl-0.8.3/bin/../lib/twurl/request_controller.rb:14:in`perform_request'
    from /usr/lib/ruby/1.8/net/http.rb:1054:in `request'
    from /usr/lib/ruby/1.8/net/http.rb:2144:in`reading_body'
    from /usr/lib/ruby/1.8/net/http.rb:1053:in `request'
    from /usr/lib/ruby/1.8/net/http.rb:1037:in`request'
    from /usr/lib/ruby/1.8/net/http.rb:543:in `start'
    from /usr/lib/ruby/1.8/net/http.rb:1035:in`request'
    from /usr/lib/ruby/gems/1.8/gems/twurl-0.8.3/bin/../lib/twurl/oauth_client.rb:80:in `perform_request_from_options'
    from /usr/lib/ruby/gems/1.8/gems/twurl-0.8.3/bin/../lib/twurl/request_controller.rb:13:in`perform_request'
    from /usr/lib/ruby/gems/1.8/gems/twurl-0.8.3/bin/../lib/twurl/request_controller.rb:9:in `dispatch'
    from /usr/lib/ruby/gems/1.8/gems/twurl-0.8.3/bin/../lib/twurl/abstract_command_controller.rb:7:in`dispatch'
    from /usr/lib/ruby/gems/1.8/gems/twurl-0.8.3/bin/../lib/twurl/cli.rb:38:in `dispatch'
    from /usr/lib/ruby/gems/1.8/gems/twurl-0.8.3/bin/../lib/twurl/cli.rb:21:in`run'
    from /usr/lib/ruby/gems/1.8/gems/twurl-0.8.3/bin/twurl:4
    from /usr/bin/twurl:19:in `load'
    from /usr/bin/twurl:19

**Comment by andypiper** [comment]
Closing for age / inability to repro - please open a new issue if this still occurs with 0.9.3
