### ISSUE TITLE
Feature request: Pretty print output

### ISSUE THREAD

**Issue by leobantech** [twitter/twurl#4]
It would be nice if twurl had an option to reformat the output to be more human readable.  Just parse the JSON / XML enough to add newlines and indenting.  No semantic understanding needed.

**Comment by andypiper** [comment]
Two possible options here:

1. Use [these shell aliases](https://gist.github.com/andypiper/32bdb4c7f0b8d65385fc7c8fa3988083#file-prettify-twurl-md)

2. Pipe output to [jq](https://stedolan.github.io/jq/).
