### ISSUE TITLE
Support app-only authentication

### ISSUE THREAD

**Issue by ryangreenberg** [twitter/twurl#47]
Allow twurl to make OAuth 2 app-only requests as described at https://dev.twitter.com/docs/auth/application-only-auth.

**Comment by verdeairo** [comment]
In version 0.9.3, how do I get the app-only? I see the commit below, but from latest master branch, I cant see this commit. How do I go about to have a twurl with app-only option available?

https://github.com/twitter/twurl/pull/48/commits/c4fb7c2709819c879b8ed839cf70bc37489cd51d

**Comment by andypiper** [comment]
@ryangreenberg any thoughts on completing this implementation... or helping to wrangle the options above? 😃

**Comment by devdazed** [comment]
its been over 5 years, any chance this will get added? is there a workaround for this?

**Comment by smaeda-ks** [comment]
I'm trying to get this done: https://github.com/twitter/twurl/pull/132

Any comments/ideas are welcome.

**Comment by smaeda-ks** [comment]
https://rubygems.org/gems/twurl/versions/0.9.5
We've published a new version, closing.
