### ISSUE TITLE
Post Tweet with Media and Geo Tag

### ISSUE THREAD

**Issue by wally68** [twitter/twurl#55]
Hello,

I would like to be able to post a tweet with an image and that is geo-tagged.

twurl -X POST "/1.1/statuses/update_with_media.json" --file pic.png -file-field "media[]" -d "status=Hello" geocode=39.45,-95.16

Thanks.

**Comment by jaakko-sf** [comment]
There is nothing that prevents using `twurl` with the [statuses/update_with_media](https://dev.twitter.com/rest/reference/post/statuses/update_with_media) as it is today. A couple of notes:

- The [statuses/update_with_media](https://dev.twitter.com/rest/reference/post/statuses/update_with_media) is deprecated. You should be using [statuses/update](https://dev.twitter.com/rest/reference/post/statuses/update) and the [media/upload](https://dev.twitter.com/rest/reference/post/media/upload) endpoint.
- Geo-tagging a Tweet works on both endpoints (`update_with_media` and `update`), but you need to pass the `lat` and `long` into the lat/long params, not a "geo" param. You also need to pass it in a `-d` option.
- Geo-tagging must be enabled on the Twitter handle in order for geo-tagging to be allowed. See [statuses/update](https://dev.twitter.com/rest/reference/post/statuses/update)

Post questions on using those endpoints at https://twittercommunity.com/c/rest-api

**Comment by andypiper** [comment]
Closing for age / inability to repro - please open a new issue if this still occurs with 0.9.3
