### ISSUE TITLE
twurl and php 

### ISSUE THREAD

**Issue by 7Style** [twitter/twurl#56]
Hi, Can I use TWURL in PHP?

**Comment by caniszczyk** [comment]
twurl is a CLI utility to work with the Twitter API.

If your'e looking for Twitter API libraries in PHP, check out this link:
https://dev.twitter.com/overview/api/twitter-libraries

**Comment by andypiper** [comment]
You can also find some cool code samples (including PHP) here https://github.com/twitterdev/api-rosetta-code and here https://twitterdev.github.io/
