### ISSUE TITLE
Running Gems

### ISSUE THREAD

**Issue by HamishMacEwan** [twitter/twurl#6]
Hi,

This isn't your problem, but nothing else I've tried has come back with any help, so before I tear my hair completely out perhaps you could point me in the right direction.

Blindly following instructions I have installed oauth and twurl gems, this tells me so:

l$ gem list --local

**\* LOCAL GEMS ***

oauth (0.4.2)
twurl (0.6.1)

But any attempt to run these on the command line gives the following results:

$ oauth
No command 'oauth' found, did you mean: blah blah blah

$ twurl
twurl: command not found

Now I'm sure there is something humiliatingly obvious that I've missed, as I say, just a pointer in the right direction is all I need.  

Hamish.

**Comment by andypiper** [comment]
Closing for age / inability to repro - please open a new issue if this still occurs with 0.9.3

**Comment by antonyggvzvmnxxcx** [comment]
Account number      New card                               
14599120
Sort code 
60-18-01
 Cvs/ 643
