### ISSUE TITLE
Issue using authorize on Windows 7

### ISSUE THREAD

**Issue by GSmedleyfx** [twitter/twurl#61]
When using authorize with a consumer key and a secret key, i ran into an issue 

C:\Users\Graeme>twurl authorize --consumer-key "{a key}" \ --consumer-secret "{another key}"
Go to {a url} and paste in the supplied PIN
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twurl-0.9.3/lib/twurl/oauth_client.rb:138:in 'perform_pin_authorize_workflow': private method 'gets' called for Twurl::CLI:Class (NoMethodError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twurl-0.9.3/lib/twurl/oauth_client.rb:125:in 'rescue in exchange_credentials_for_access_token'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twurl-0.9.3/lib/twurl/oauth_client.rb:122:in 'exchange_credentials_for_access_token'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twurl-0.9.3/lib/twurl/authorization_controller.rb:6:in 'dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twurl-0.9.3/lib/twurl/abstract_command_controller.rb:7:in 'dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twurl-0.9.3/lib/twurl/cli.rb:38:in 'dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twurl-0.9.3/lib/twurl/cli.rb:21:in 'run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/twurl-0.9.3/bin/twurl:4:in '<top (required)>'
        from C:/Ruby22-x64/bin/twurl:23:in 'load'
        from C:/Ruby22-x64/bin/twurl:23:in '<main>'

I managed to fix it by replacing
`pin = gets`
on line 138 of oauth_client.rb with
`pin = $stdin.gets`
though I'm not sure if this change would break in other environments.
I'm new to contributing to open-source software, so I apologize in advance if i should have simply forked and created a pull request, or if this is otherwise the wrong place.

**Comment by lotfire** [comment]
thanks for the tip!
it worked for me

**Comment by dalayach** [comment]
Is there any way to get this onto the official build?
