### ISSUE TITLE
Trouble getting twurl utility working with Ads API Advertiser API api ads

### ISSUE THREAD

**Issue by frewsxcv** [twitter/twurl#66]
```
coreyf@frewbook-pro /tmp> gem i twurl --source http://rubygems.org
Successfully installed twurl-0.9.3
Parsing documentation for twurl-0.9.3
Done installing documentation for twurl after 0 seconds
1 gem installed
```

```
coreyf@frewbook-pro /tmp> twurl authorize --consumer-key [my consumer key] --consumer-secret [my secret key]
Go to [url here] and paste in the supplied PIN
[pin here]
Authorization successful
```

```
coreyf@frewbook-pro /tmp> twurl -H ads-api-sandbox.twitter.com /0/accounts/
{"errors":[{"code":"UNAUTHORIZED_CLIENT_APPLICATION","message":"The client application making this request does not have access to this API"}],"request":{"params":{}}}
```

Why does my client not have access to this API?

**Comment by brandonblack** [comment]
@frewsxcv the application you're using may not have access to the Ads API. What's your consumer key or app ID?

**Comment by frewsxcv** [comment]
Consumer key: yp0xQ7dGIJwl7aZXXrOyDkeVi

**Comment by brandonblack** [comment]
@frewsxcv I'm unable to locate that consumer key. Your app doesn't appear to exist.

Since this isn't really the correct place to solve this, you should head over to the Twitter community forums to figure out what's going on.

https://twittercommunity.com/c/advertiser-api

**Comment by frewsxcv** [comment]
> I'm unable to locate that consumer key. Your app doesn't appear to exist.

Here are the screenshots of ever page on the app settings page:

![screen shot 2015-11-10 at 4 57 55 pm](https://cloud.githubusercontent.com/assets/416575/11077121/6913b768-87cc-11e5-8864-d2173a7daa09.png)

![screen shot 2015-11-10 at 4 57 47 pm](https://cloud.githubusercontent.com/assets/416575/11077125/6d7e89cc-87cc-11e5-987d-8b24d693d855.png)
![screen shot 2015-11-10 at 4 56 41 pm](https://cloud.githubusercontent.com/assets/416575/11077132/711d194a-87cc-11e5-80c6-57eadb6f6147.png)
![screen shot 2015-11-10 at 4 56 34 pm](https://cloud.githubusercontent.com/assets/416575/11077136/7519a27a-87cc-11e5-9420-b69bde97e5f8.png)

>  you should head over to the Twitter community forums to figure out what's going on.

I have already headed over to the Twitter community forums to figure out what's going on. Here are three **unanswered** threads on this issue:

* https://twittercommunity.com/t/authorization-problem/55197/4
* https://twittercommunity.com/t/cant-connect-to-the-twitter-ads-api/55709/3
* https://twittercommunity.com/t/trouble-getting-twurl-utility-working-with-ads-api/55591 (mine)

In addition, [I asked another Ads API question](https://twittercommunity.com/t/help-with-understanding-targeting-criteria-api-response/55589/) over a week ago which is more pressing and has not received a response from Twitter. Not to mention the countless other recent unaddressed questions on the forum.

**Comment by brandonblack** [comment]
@frewsxcv you just shared your consumer secret with the whole world :(

You should delete this post immediately, and reset your consumer key and token (bottom of the Keys and Tokens tab).

**Comment by frewsxcv** [comment]
In which screenshot did I share my consumer secret?

**Comment by brandonblack** [comment]
@frewsxcv you app doesn't have access. You need to follow up in the forums. Your issue can't be resolved here.
