### ISSUE TITLE
Error 32 in /1.1/statuses/update.json

### ISSUE THREAD

**Issue by izumariu** [twitter/twurl#70]
I want to POST a status via twurl but everything I get is
{"errors":[{"code":32,"message":"Could not authenticate you."}]}.
I checked my consumer key and secret multiple times, still it doesn't work. Does anyone know what's wrong?

**Comment by ryangreenberg** [comment]
This is a common problem when the access token or secret are no longer valid for whatever reason. I recommend re-running twurl authorize for the user in question (or copying your token and secret from https://apps.twitter.com into your .twurlrc file.
