### ISSUE TITLE
Tweet from other profile without set default

### ISSUE THREAD

**Issue by realKSMC** [twitter/twurl#72]
Is there an option to e.g. tweet from another profile without set default before?

Like @tester222 needs to tweet "hi".
The default is @tester111.

How to tweet as @tester222 without twurl set default tester222 before?

**Comment by AdamSt12** [comment]
Does https://github.com/twitter/twurl/issues/10 do what you want?

Otherwise see https://github.com/twitter/twurl/issues/19 which is a request to use a different set of credentials.
