### ISSUE TITLE
Tweet with image fails with error 32

### ISSUE THREAD

**Issue by DSotnikov** [twitter/twurl#73]
My tweets without images work fine and with images fail.

I'd uploaded my image:

> $ twurl -H upload.twitter.com -X POST "/1.1/media/upload.json" --file "../../../blog/API SDK download in Developer Portal.png" --file-field "media"
> {"media_id":852314091490168833,"media_id_string":"852314091490168833","size":94927,"expires_after_secs":86400,"image":{"image_type":"image\/png","w":914,"h":646}}

Then when I twurl without the image - this works great.

With the image - it fails:

> $ twurl "/1.1/statuses/update.json" -d "media_ids=852314091490168833&status=Sample Tweet with media_ids and twurl"
> {"errors":[{"code":32,"message":"Could not authenticate you."}]}

The application has both Read and Write permissions.

Any ideas on what's going on?

**Comment by andypiper** [comment]
Not sure - I've just performed the exact same test locally, and the same two steps worked fine. Anything additional if you trace out the commands with the -t flag?

**Comment by DSotnikov** [comment]
Hm... Right now it wouldn't tweet with or without permission. Same error 32 even though it says initially that authorization is OK:

> $ twurl authorize --consumer-key ikufCY4TELGAhR6o1Popxxxxx --consumer-secret 1SJKblSSAwfsCnCyWsFzB8cr4nudQMgXGzShqbmJA1yyvxxxxx
> Go to https://api.twitter.com/oauth/authorize?oauth_consumer_key=ikufCY4TELGAhxxxxxxx&oauth_nonce=Cex8W66i7SZhsp4gqt8J4UaB9w7UJM1Ar8V7Yxxxxx&oauth_signature=pGCa%252FNtNbu9l%252FpzPS%252BE5a9GJGOY%xxxx&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1492115644&oauth_token=eppLEgAAAAAA0Gy0AAABxxxxx&oauth_version=1.0 and paste in the supplied PIN
> 6863335
> Authorization successful
> $ 
> $ twurl "/1.1/statuses/update.json" -d "media_ids=852314091490168833&status=Sample Tweet with media_ids and twurl" -t
> opening connection to api.twitter.com:443...
> opened
> starting SSL for api.twitter.com:443...
> SSL established
> <- "POST /1.1/statuses/update.json HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: OAuth gem v0.5.1\r\nContent-Type: application/x-www-form-urlencoded\r\nAuthorization: OAuth oauth_consumer_key=\"HAY0vafCDIGTGgeD77jxxxxxx\", oauth_nonce=\"u8gxISXYwdmEWQXe7NEQDFhykdObpH3mk100saxxxx\", oauth_signature=\"Sjm0SSCHOhoJxKE1YZfkxxxxx%3D\", oauth_signature_method=\"HMAC-SHA1\", oauth_timestamp=\"1492115706\", oauth_token=\"17675386-snhvO370ZmtKD3Do4OWLuDyyfVPQxveCWZrNxxxxx\", oauth_version=\"1.0\"\r\nConnection: close\r\nHost: api.twitter.com\r\nContent-Length: 73\r\n\r\n"
> <- "media_ids=852314091490168833&status=Sample+Tweet+with+media_ids+and+twurl"
> -> "HTTP/1.1 401 Authorization Required\r\n"
> -> "connection: close\r\n"
> -> "content-encoding: gzip\r\n"
> -> "content-type: application/json; charset=utf-8\r\n"
> -> "date: Thu, 13 Apr 2017 20:35:06 GMT\r\n"
> -> "server: tsa_a\r\n"
> -> "set-cookie: guest_id=v1%3A149211570666565703; Domain=.twitter.com; Path=/; Expires=Sat, 13-Apr-2019 20:35:06 UTC\r\n"
> -> "strict-transport-security: max-age=631138519\r\n"
> -> "transfer-encoding: chunked\r\n"
> -> "x-connection-hash: d755ad5310059e7bba7f2655684763b8\r\n"
> -> "x-response-time: 8\r\n"
> -> "x-tsa-request-body-time: 63\r\n"
> -> "\r\n"
> -> "4f\r\n"
> reading 79 bytes...
> -> ""
> -> "\x1F\x8B\b\x00\x00\x00\x00\x00\x00\x00\xAAVJ-*\xCA/*V\xB2\x8A\xAEVJ\xCEOIU\xB226\xD2Q\xCAM-.NL\ar\x94\x9C\xF3KsR\x14\xF2\xF2K\x14\x12KK2R\xF3J2\x93\x13KR\x15*\xF3K\xF5\x94jck\x01\x00\x00\x00\xFF\xFF"
> read 79 bytes
> reading 2 bytes...
> -> ""
> -> "\r\n"
> read 2 bytes
> -> "a\r\n"
> reading 10 bytes...
> -> ""
> -> "\x03\x00\n\xF0^\f@\x00\x00\x00"
> **{"errors":[{"code":32,"message":"Could not authenticate you."}]}**read 10 bytes
> reading 2 bytes...
> -> ""
> -> "\r\n"
> read 2 bytes
> -> "0\r\n"
> -> "\r\n"
> Conn close
> $ 
> $ twurl "/1.1/statuses/update.json" -d "status=Test, please ignore" -t
> opening connection to api.twitter.com:443...
> opened
> starting SSL for api.twitter.com:443...
> SSL established
> <- "POST /1.1/statuses/update.json HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: OAuth gem v0.5.1\r\nContent-Type: application/x-www-form-urlencoded\r\nAuthorization: OAuth oauth_consumer_key=\"HAY0vafCDIGTGgeD77jxxxxx\", oauth_nonce=\"g25Uqva67op8LmkktNHNpgFXW3XvyzrDwu1gxxxxx\", oauth_signature=\"x6EQWtDBR56U62iRS4V8xxxxxx%3D\", oauth_signature_method=\"HMAC-SHA1\", oauth_timestamp=\"1492115780\", oauth_token=\"17675386-snhvO370ZmtKD3Do4OWLuDyyfVPQxveCWZrNxxxxxxx\", oauth_version=\"1.0\"\r\nConnection: close\r\nHost: api.twitter.com\r\nContent-Length: 28\r\n\r\n"
> <- "status=Test%2C+please+ignore"
> -> "HTTP/1.1 401 Authorization Required\r\n"
> -> "connection: close\r\n"
> -> "content-encoding: gzip\r\n"
> -> "content-length: 89\r\n"
> -> "content-type: application/json; charset=utf-8\r\n"
> -> "date: Thu, 13 Apr 2017 20:36:20 GMT\r\n"
> -> "server: tsa_a\r\n"
> -> "set-cookie: guest_id=v1%3A149211578092265890; Domain=.twitter.com; Path=/; Expires=Sat, 13-Apr-2019 20:36:20 UTC\r\n"
> -> "strict-transport-security: max-age=631138519\r\n"
> -> "x-connection-hash: d7e303705b9519207347f2f6ef6ba2d2\r\n"
> -> "x-response-time: 7\r\n"
> -> "x-tsa-request-body-time: 100\r\n"
> -> "\r\n"
> reading 89 bytes...
> -> ""
> -> "\x1F\x8B\b\x00\x00\x00\x00\x00\x00\x00\xAAVJ-*\xCA/*V\xB2\x8A\xAEVJ\xCEOIU\xB226\xD2Q\xCAM-.NL\ar\x94\x9C\xF3KsR\x14\xF2\xF2K\x14\x12KK2R\xF3J2\x93\x13KR\x15*\xF3K\xF5\x94jck\x01\x00\x00\x00\xFF\xFF\x03\x00\n\xF0^\f@\x00\x00\x00"
> {"errors":[{"code":32,"message":"Could not authenticate you."}]}read 89 bytes
> Conn close
> $

**Comment by JulianTapales** [comment]
Is there any news on this? @DSotnikov were you able to find a solution?

**Comment by DSotnikov** [comment]
Nope. I am still stuck with tweets without images.

**Comment by smaeda-ks** [comment]
Since no one was able to diagnose it, I'm closing this issue for the time being.

**Comment by jakoritarleite** [comment]
sou gay

**Comment by 0x00002152** [comment]
go ahead and reopen it because its not fixed

**Comment by andypiper** [comment]
Can you provide any additional diagnosis information, including the steps you’ve been through?

**Comment by weltonmattos** [comment]
**media_ids** is a String, not number. 
And use **media_id_string** instead **media_id**
-
I had the same problem, and it worked after this changes.

**Comment by weltonmattos** [comment]
**media_ids** is a String, not number. And use **media_id_string** instead **media_id**. I had the same problem, and it worked after this changes.
