### ISSUE TITLE
Parsing certain fields

### ISSUE THREAD

**Issue by arpan-ghosh** [twitter/twurl#74]
Is there a way to use Twurl to parse only certain fields from the JSON? I want to run something like 
`twurl "/1.1/statuses/show/[TWEET ID].json"`

and have it spit out only the following from the json:

 "id_str", "text", "location", "geo", "coordinates", and "place"?

**Comment by andypiper** [comment]
yes, but you'd need to use something to help you - I use [jq](https://stedolan.github.io/jq/).

I've got a bunch of "recipes" in [this Gist](https://gist.github.com/andypiper/32bdb4c7f0b8d65385fc7c8fa3988083) that you may find helpful.

**Comment by arpan-ghosh** [comment]
Thanks for the help!
