### ISSUE TITLE
Doesn't seem possible to use this to upload to chunked service (upload.twitter.com)?

### ISSUE THREAD

**Issue by bobber205** [twitter/twurl#86]
As far as I can tell the twurl tool doesn't want you to provide the domain, just the relative path.

I can't get it to run the INIT command:

```
twurl -X POST https://upload.twitter.com/1.1/media/upload.json -d "command=INIT&total_bytes=10240&media_type=image/jpeg"
```

Is there something I need to do to get it recognize this as a valid command?

**Comment by AdamSt12** [comment]
Generally specify the host with -H, so
`twurl -H upload.twitter.com -X POST /1.1/media/upload.json -d "command=INIT&total_bytes=10240&media_type=image/jpeg"`

**Comment by andypiper** [comment]
There's a [tutorial](https://developer.twitter.com/en/docs/tutorials/uploading-media) on using `twurl` to upload media on the developer website.
