### ISSUE TITLE
Use $stdin.gets instead of gets in oauth_client.rb

### ISSUE THREAD

**Issue by whitopiggu** [twitter/twurl#95]
When authorizing with twurl, gets is called to get user input for the authorization PIN, but returns a file not found error.

Expected behavior:
gets will read stdin for the PIN.
Actual behavior:
gets looks for a file and returns a "file not found" error, aborting the authorization process.
Attempt to use `twurl authorize -u username -p password -c key -s secret -a token -S secret`
Fix:
The problematic line is line 138 in /lib/twurl/oauth_client.rb. Changing it from
`      pin = gets`
to
`      pin = $stdin.gets`
causes it to behave as expected, and allow the user to input the pin and complete the authorization process.

**Comment by smaeda-ks** [comment]
https://github.com/twitter/twurl/releases/tag/v0.9.4

Closing.
